[build.environment]
  URL = "https://cryptic-island-45793.herokuapp.com"
  REACT_APP_GOOGLE_GEOCODE_API_KEY = "AIzaSyAkZI07elJzbOUJR5DCnSDGTZuDGmcptBM"
  REACT_APP_BETTER_DOC_API_KEY = "376761dc9a0b6db741da0e97bfad107e"